version: '3'

services:
  authenticationDB:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 10s
      retries: 10
    ports:
      - 3306:3306
    volumes:
      - authdata:/var/lib/mysql
    networks:
      - authnet
  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - authnet
  adminer1:
    image: adminer
    ports:
      - 8081:8080
    networks:
      - shopnet
  authenticationDBmigration:
    build:
      context: .
      dockerfile: authenticationDBmigration.dockerfile
    image: authenticationdbmigration
    environment:
      - DATABASE_URL=authenticationDB
    depends_on:
      authenticationDB:
        condition: service_healthy
    networks:
      - authnet
  authentication:
    build:
      context: .
      dockerfile: authentication.dockerfile
    image: authentication
    environment:
      - DATABASE_URL=authenticationDB
    depends_on:
      - authenticationDBmigration
    ports:
      - 5000:5000
  spark-master:
    image: bde2020/spark-master:3.3.0-hadoop3.3
    container_name: spark-master
    ports:
      - 8082:8080
      - 7077:7077
    environment:
      - INIT_DAEMON_STEP=setup_spark
  spark-worker-1:
    image: bde2020/spark-worker:3.3.0-hadoop3.3
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - 8083:8081
    environment:
      - SPARK_MASTER=spark://spark-master:7077
  spark-worker-2:
    image: bde2020/spark-worker:3.3.0-hadoop3.3
    container_name: spark-worker-2
    depends_on:
      - spark-master
    ports:
      - 8084:8081
    environment:
      - SPARK_MASTER=spark://spark-master:7077
  shopDB:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3307:3306
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 10s
      retries: 10
    volumes:
      - shopdata:/var/lib/mysql
    networks:
      - shopnet
  shopDBmigration:
    build:
      context: .
      dockerfile: shopDBmigartion.dockerfile
    image: shopdbmigration
    environment:
      - DATABASE_URL=shopDB
    depends_on:
      shopDB:
        condition: service_healthy
    networks:
      - shopnet
  owner:
    build:
      context: .
      dockerfile: owner.dockerfile
    image: owner
    environment:
      - DATABASE_URL=shopDB
      - PRODUCTION=True
    depends_on:
      - shopDBmigration
    ports:
      - 5001:5001
    networks:
      - shopnet
  customer:
    build:
      context: .
      dockerfile: customer.dockerfile
    image: customer
    environment:
      - DATABASE_URL=shopDB
    depends_on:
      - shopDBmigration
    ports:
      - 5002:5002
    networks:
      - shopnet
  courier:
    build:
      context: .
      dockerfile: courier.dockerfile
    image: courier
    environment:
      - DATABASE_URL=shopDB
    depends_on:
      - shopDBmigration
    ports:
      - 5003:5003
    networks:
      - shopnet

volumes:
  authdata:
  shopdata:
networks:
  authnet:
  shopnet:
